apiVersion: v1
kind: Pod
metadata:
  name: shop-with-tail-sidecar
spec:
  containers:
  - name: main-clerk
    image: busybox:1.28
    args:
    - /bin/sh
    - -c
    - "while true; do echo $(date) - Custom sale recorded >> /var/log/main-container.log; sleep 5; done"
    volumeMounts:
    - name: varlog
      mountPath: /var/log
  - name: log-tailer-sidecar
    image: busybox:1.28
    args: [/bin/sh, -c, 'tail -f /var/log/main-container.log']
    volumeMounts:
    - name: varlog
      mountPath: /var/log
  volumes:
  - name: varlog
    emptyDir: {}
