apiVersion: v1
kind: Pod
metadata:
  labels:
    run: sidecar-example
  name: sidecar-example
spec:
  initContainers:
  - name: init-myfile
    image: busybox
    command:
    - sh
    - -c
    - echo "Hello from Init" > /data/index.html
    volumeMounts:
    - name: shared-data
      mountPath: /data
  containers:
  - image: nginx
    name: sidecar-example
    ports:
    - containerPort: 80
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
  - name: sidecar-helper
    image: busybox
    command:
    - sh
    - -c
    - tail -f /dev/null
    volumeMounts:
    - name: shared-data
      mountPath: /data
  volumes:
  - name: shared-data
    emptyDir: {}
