apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: app-pod
  name: app-pod
spec:
  containers:
  - image: nginx:1.29.0
    name: app-pod
    resources: {}
    envFrom:
    - configMapRef:
        name: app-config
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
