apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: warehouse-pvc
  namespace: mall-shops
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
     storage: 500Mi
