apiVersion: v1
kind: Pod
metadata:
  labels:
    run: probed
  name: probed
spec:
  containers:
  - image: nginx
    name: probed
    ports:
    - containerPort: 80
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 30
      periodSeconds: 10
  restartPolicy: Never
