apiVersion: v1
kind: Service
metadata:
  labels:
    app: boutique
  name: boutique
spec:
  clusterIP: None
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: boutique
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: boutique
  name: boutique
spec:
  serviceName: boutique
  replicas: 3
  selector:
    matchLabels:
      app: boutique
  template:
    metadata:
      labels:
        app: boutique
    spec:
      containers:
      - image: nginx:alpine
        name: boutique
        resources: {}
        volumeMounts:
        - name: boutique-locker
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: boutique-locker
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 1Gi
status: {}
