apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: my-app
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mall
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mall
    spec:
      containers:
      - image: nginx:alpine
        name: nginx
        resources: {}
status: {}
